INSERT INTO
    database_development.pets (
        pets_id,
        name,
        pet_type,
        breed,
        status,
        age,
        sex,
        size,
        good_with_dogs,
        good_with_cats,
        good_with_kids,
        indoor_or_outdoor,
        housetrained,
        description,
        date_surrendered,
        date_adopted,
        date_deceased,
        notes,
        attention,
        image
    )
VALUES
  (
        1,
        "Leo",
        "Dog",
        "German Shepard",
        "Available",
        5,
        "Male",
        "65 lbs",
        true,
        true,
        False,
        "indoor",
        true,
        "German Shepard Husky dropped off by owner that is unable to keep him. Shows signs of fear aggression and must be in a home with no kids. Well house trained and knows many commands.",
        "2004-05-23T14:25:10",
        null,
        null,
        "Working with trainer Ram for fear aggression",
        null,
        "/pet_images/Leo.jpg"
    ),

(
        2,
        "Wilbur",
        "Dog",
        "German Shepard",
        "Available",
        2,
        "Male",
        "55 lbs",
        true,
        true,
        true,
        "indoor",
        true,
        "White German Sheppard with medical issues involving intestinal tract so in need of a caring home for proper care. Extremely friendly and confident. Loves other dogs, children, and strangers.",
        "2004-05-23T14:25:10",
        null,
        null,
        "Anal tear due to foreign object. Intestinal damage is permanent.",
        null,
        "/pet_images/Wilbur.jpg"
    ),

(
        3,
        "Lanny",
        "Dog",
        "Doberman",
        "Available",
        1,
        "Female",
        "30 lbs",
        true,
        true,
        true,
        "indoor",
        true,
        "Doberman puppy coming in through local litter. Loves toys, wrestling, and is extremely friendly. Is partly potty trained and knows basic commands.",
        "2004-05-23T14:25:10",
        null,
        null,
        null,
        null,
        "/pet_images/Lanny.jpg"
    ),

(
        4,
        "Island",
        "Dog",
        "Mixed",
        "Available",
        0.5,
        "Female",
        "20 lbs",
        true,
        true,
        true,
        "indoor",
        true,
        "Believe to be a Doberman pitt mix. Very Nervous and scared of strangers but very confident when comfortable. Loves toys, treats, and snuggles.",
        "2004-05-23T14:25:10",
        null,
        null,
        null,
        null,
        "/pet_images/Island.jpg"
    ),

(
        5,
        "Peach",
        "Cat",
        "Siamese",
        "Available",
        3,
        "Female",
        "10 lbs",
        true,
        true,
        false,
        "indoor",
        true,
        "Very skittish and not fond of strangers. Extremely sweet and loves cuddles. Requires a lot of attention due to high energy.",
        "2004-05-23T14:25:10",
        null,
        null,
        null,
        null,
        "/pet_images/Peach.jpg"
    ),

(
        6,
        "Bau",
        "Cat",
        "tabby",
        "Available",
        3,
        "Female",
        "10 lbs",
        true,
        true,
        true,
        "indoor",
        true,
        "High energy and extremely friendly. Loves everyone and will do anything for food.",
        "2004-05-23T14:25:10",
        null,
        null,
        null,
        null,
        "/pet_images/Bau.jpg"
    )