INSERT INTO
    database_development.pets (
        pets_id,
        name,
        pet_type,
        breed,
        status,
        age,
        sex,
        size,
        good_with_dogs,
        good_with_cats,
        good_with_kids,
        indoor_or_outdoor,
        housetrained,
        description,
        date_surrendered,
        date_adopted,
        date_deceased,
        notes,
        attention,
        image
    )
VALUES
    (
        1,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    ),
    (
        2,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    ),
    (
        3,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    ),
    (
        4,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    ),
    (
        5,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    ),
    (
        6,
        "Mr. Fuzzy",
        "Dog",
        "Husky",
        "Available",
        2,
        "Female",
        "70 lbs",
        false,
        false,
        true,
        "both",
        true,
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        7 / 12 / 2020,
        null,
        null,
        "Needs medication 7/15/2020",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg"
    );